runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

skip_files: 
- twosides_every10.tsv
- twosides_every20.tsv
- offsides.tsv
- templates/offsides_every20.json
- google-cloud-sdk/bin/
- google-cloud-sdk/lib/
- google-cloud-sdk/.install/
- google-cloud-sdk/help/
- appengine-gcs-client/